// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy5HR5imI1uMlW1_0tfynTY7ZAqs4v2bI',
    appId: '1:788744896972:web:fb4441865583f83ad39d69',
    messagingSenderId: '788744896972',
    projectId: 'fir-test-4dca4',
    authDomain: 'fir-test-4dca4.firebaseapp.com',
    storageBucket: 'fir-test-4dca4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6-5xYeBDGZA8kz_BECL7v2DmziPM4E1s',
    appId: '1:788744896972:android:b2715556337d3072d39d69',
    messagingSenderId: '788744896972',
    projectId: 'fir-test-4dca4',
    storageBucket: 'fir-test-4dca4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYyaS7bMdbkJ3pI41H7jcrsw3f6H62deg',
    appId: '1:788744896972:ios:22934b3a5cdf2948d39d69',
    messagingSenderId: '788744896972',
    projectId: 'fir-test-4dca4',
    storageBucket: 'fir-test-4dca4.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
